"""modificação da configuração do ítem DataCadastro do arquivo models.py

Revision ID: 145dfc92ff99
Revises: 7cd66861aca1
Create Date: 2024-12-19 23:36:48.361478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '145dfc92ff99'
down_revision = '7cd66861aca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registers', schema=None) as batch_op:
        batch_op.alter_column('DataCadastro',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('sobrenome',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('telefone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registers', schema=None) as batch_op:
        batch_op.alter_column('telefone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('sobrenome',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('DataCadastro',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
