"""Adicionar coluna de newsletters a tabela registers

Revision ID: 35c95dabd759
Revises: 8c2481f48511
Create Date: 2024-12-25 01:53:06.583745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35c95dabd759'
down_revision = '8c2481f48511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('newsletters', sa.Boolean(), nullable=False))
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('newsletters')

    # ### end Alembic commands ###
