"""tornar user_nome unique=True na tabela registers do arquivo models.py

Revision ID: 8c2481f48511
Revises: 145dfc92ff99
Create Date: 2024-12-19 23:50:00.774927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2481f48511'
down_revision = '145dfc92ff99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registers', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.create_unique_constraint(None, ['user_nome'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
