"""Retirar coluna confirm_senha e aumentar tamanho da coluna senha

Revision ID: b382766961cb
Revises: 35c95dabd759
Create Date: 2025-04-08 00:28:27.084123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b382766961cb'
down_revision = '35c95dabd759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registers', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=260),
               existing_nullable=False)
        batch_op.alter_column('newsletter',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Boolean(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['user_nome'])
        batch_op.drop_column('confirm_senha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirm_senha', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('newsletter',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('senha',
               existing_type=sa.String(length=260),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
